
spring:
  datasource:
    url: jdbc:mysql://192.168.5.44:3306/device_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Root@2020